name: Docker

on:
    workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        name: programa_compilado_go
        # IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both.
        
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      uses: docker/login-action@v3.4.0
      with:
        # Username used to log against the Docker registry
        username: "alanseraf"
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Sanitize Docker tag
      id: sanitize_tag
      run: |
          # Substitui todos os '/' por '-' no nome da ref.
          TAG=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
          echo "value=${TAG}" >> $GITHUB_OUTPUT
                
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      uses: docker/build-push-action@v6.18.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: alanseraf/go_ci:${{ steps.sanitize_tag.outputs.value }}
          
          
