name: Entrega continua

#PRÉ-REQUISITOS
#==> PROVISIONAR MÁQUINA VIRTUAL EC2
#==> PROVISIONAR BANCO DE DADOS RDS
#===> CONFIGURAR COMUNICAÇÃO ENTRE OS GRUPOS DE SEGURANÇA
#===> SG DA EC2 - ENTRADA: (SSH) + Todo o tráfego SG do BD + TCP (8000) qualquer ipv4
#===> SG DA EC2 - SAÍDA: Todo o tráfego
#===> SG DO BD - Entrada: Todo o tráfego do propróprio SG + PostgersSQL do SG da EC2
#===> SG DO BD - Saída: Todo o tráfego

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
    # Artifact name
        name: programa
    - uses: actions/checkout@v3
    
    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #CHAVE PRIVADA DA INSTÂNCIA EC2
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        #ENDEREÇO IPV4 PÚBLICO DA INSTÄNCIA EC2
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        #CONEXÃO DE INSTÂNCIA DO EC2 > NOME DE USUÁRIO
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "postgres-data"
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export HOST=${{ secrets.DB_HOST }}
          export USER=${{ secrets.DB_USER }}
          export PASSWORD=${{ secrets.DB_PASSWORD }}
          export DBNAME=${{ secrets.DB_NAME }}
          export DB_PORT=${{ secrets.DB_PORT }}
          export PORT=8000
          chmod +x main
          nohup ./main > nohup.out 2> nohup.err < /dev/null &
        
        
